# Generated by Django 3.1.7 on 2021-03-12 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('ANDIJON', 'andijon'), ('BUXORO', 'buxoro'), ('FARGONA', 'fargona'), ('JIZZAX', 'jizzax'), ('XORAZM', 'xorazm'), ('NAMANGAN', 'namangan'), ('NAVOIY', 'navoiy'), ('QASHQADARYO', 'qashqadaryo'), ('SAMARQAND', 'samarqand'), ('SIRDARYO', 'sirdaryo'), ('SURXONDARYO', 'surxondaryo'), ('QORAQALPOGISTON', 'qoraqalpogiston'), ('TOSHKENT_REG', 'toshkent_reg'), ('TOSHKENT_CITY', 'toshkent_city')], max_length=18)),
                ('name', models.CharField(max_length=200, null=True)),
                ('coach', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('min_birth_date', models.DateField()),
                ('max_birth_date', models.DateField()),
                ('min_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('max_weight', models.IntegerField(blank=True, default=0, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team')),
                ('match_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.matchtype')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team')),
            ],
        ),
    ]
